# Generated by Django 3.1.3 on 2020-12-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='Complete',
        ),
    ]
