# Generated by Django 3.1.3 on 2020-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201202_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Complete',
            new_name='complete',
        ),
    ]
